system:
  server:
    jetty-adapter: !system/component
      system/component-kind: server/jetty-adapter
      handler: !system/required-component
      options:
        join?: false
        port: !port 0
