system:
  message-bus: !include command-processor/message-bus-test.yml
  postgres: !include testcontainers/postgres-test.yml
  db: !include command-processor/datasource-test.yml
  migrator: !include accounts/migrator-test.yml
  avro: !include avro/avro-test.yml
  command:
    processor: !system/component
      system/component-kind: accounts/processor
      datasource: !system/ref migrator.migrations
      schemas: !system/ref avro.serde
