system:
  pulsar: !include testcontainers/pulsar-all-test.yml
  message-bus: !include command-processor/message-bus-test.yml
  postgres: !include testcontainers/postgres-test.yml
  db: !include command-processor/datasource-test.yml
  migrator: !include processor/migrator-test.yml
  avro: !include avro/avro-test.yml
  processor:
    datasource: !system/ref migrator.migrations
    schemas: !system/ref avro.serde
