system:
  postgres: !include testcontainers/postgres-test.yml
  db: !include db/postgres/datasource-test.yml
  migrator:
    migrations: !system/component
      system/component-kind: migrator/migrations
      datasource: !system/ref db.datasource
      changelogs:
        - schemas/iam/init-changelog.sql
