system:
  fdb: !include testcontainers/fdb-test.yml
  avro: !include avro/avro-test.yml
  accounts:
    watcher-handler: !system/required-component
    processor: !system/component
      system/component-kind: accounts/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
    watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      consumer-id: accounts-watcher
      store-name: accounts
      handler: !system/local-ref watcher-handler
