system:
  fdb: !include testcontainers/fdb-test.yml
  avro: !include avro/avro-test.yml
  accounts:
    processor: !system/component
      system/component-kind: accounts/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
