apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xqueenswoodcertificates.platform.queenswood.repldriven.com
spec:
  scope: Namespaced
  group: platform.queenswood.repldriven.com
  names:
    kind: XQueenswoodCertificate
    plural: xqueenswoodcertificates
  defaultCompositionRef:
    name: xqueenswoodcertificate.gcp
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [domain, location, managedZoneRef]
              properties:
                domain: { type: string }
                location: { type: string }
                managedZoneRef:
                  type: object
                  required: [name]
                  properties:
                    name: { type: string }
            status:
              type: object
              properties:
                dnsRecord:
                  type: object
                  properties:
                    name: { type: string }
                    data: { type: string }
