system:
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  bootstrap: !include bank/bootstrap-internal-test.yml
  payment:
    processor: !system/component
      system/component-kind: payment/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
