system:
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  queenswood:
    bootstrap: !system/component
      system/component-kind: queenswood/bootstrap
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      organization-name: Queenswood
      party-display-name: Queenswood
      product-name: Internal Account
      account-type: account-type-current
      balance-sheet-side: balance-sheet-side-liability
      currency: GBP
      balance-products:
        - balance-type: balance-type-default
          balance-status: balance-status-posted
