system:
  message-bus: !include uk-companies-house-adapter/message-bus-test.yml
  avro: !include avro/avro-test.yml
  fdb: !include bank/fdb-test.yml
  server: !include uk-companies-house-adapter/simulator-test.yml
  company-registries:
    command-processor-impl: !system/component
      system/component-kind: uk-companies-house-adapter/command-processor
      schemas: !system/ref avro.serde
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      companies-house-url: !system/ref server.http-url
    command-processor: !system/component
      system/component-kind: command-processor/command-processor
      bus: !system/ref message-bus.bus
      processor: !system/local-ref command-processor-impl
      command-channel: !keyword company-registries-command
      command-response-channel: !keyword company-registries-command-response
    dispatcher: !system/component
      system/component-kind: command/dispatcher
      bus: !system/ref message-bus.bus
      command-channel: !keyword company-registries-command
      command-response-channel: !keyword company-registries-command-response
