system:
  avro: !include system/avro.yml
  companies-dispatcher: !include system/company-dispatcher.yml
  fdb: !include system/fdb-test.yml
  message-bus: !include uk-companies-house-adapter/message-bus-test.yml
  uk-companies-house-adapter: !include system/uk-companies-house-adapter.yml
  uk-companies-house-simulator-server: !include system/uk-companies-house-simulator-server.yml
