system:
  fdb: !include system/fdb.yml
  avro: !include system/avro.yml
  scheduler:
    scheduler: !system/component
      system/component-kind: scheduler/scheduler
  bank-scheduler:
    runner: !system/component
      system/component-kind: bank-scheduler/runner
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
      scheduler: !system/ref scheduler.scheduler
  telemetry: !include system/telemetry.yml
