system:
  pulsar: !include bank-monolith/pulsar-test.yml
  message-bus: !include bank-monolith/message-bus-test.yml
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  cash-accounts: !include bank/cash-account-test.yml
  parties: !include bank/party-test.yml
  payments: !include bank/payment-test.yml
  interest: !include bank/interest-test.yml
  transactions: !include bank/transaction-test.yml
  idv: !include bank/idv-test.yml
  tiers: !include bank/tier-test.yml
  policies: !include bank/policy-test.yml
  policy-bindings: !include bank/policy-binding-test.yml
  organizations: !include bank/organization-test.yml
  telemetry:
    otel-sdk: !profile
      dev: !system/component
        system/component-kind: telemetry/otel-sdk
        service-name: bank-monolith
        endpoint: http://localhost:4318/v1/traces
  server:
    handler: !system/required-component
    interceptors: !system/component
      system/component-kind: server/interceptors
      admin-api-key: !env MONO_ADMIN_API_KEY
      internal-organization-id: !system/ref organizations.internal.organization.organization-id
      internal-account-id: !system/ref organizations.internal-account-id
      dispatchers:
        cash-accounts: !system/ref cash-accounts.dispatcher
        parties: !system/ref parties.dispatcher
        payments: !system/ref payments.dispatcher
        interest: !system/ref interest.dispatcher
        transactions: !system/ref transactions.dispatcher
      avro: !system/ref avro.serde
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      clearbank-adapter-url: !system/ref clearbank-adapter-server.http-url
    jetty-adapter: !system/component
      system/component-kind: server/jetty-adapter
      handler: !system/ref server.handler
      interceptors: !system/ref server.interceptors
      options: !profile
        dev:
          port: 8080
        default:
          port: 0
  clearbank-simulator-server: !include bank-monolith/clearbank-simulator-test.yml
  clearbank-adapter-server: !include bank-monolith/clearbank-adapter-server-test.yml
  clearbank-adapter: !include bank-monolith/clearbank-adapter-test.yml
