apiVersion: dns.gcp.m.upbound.io/v1beta1
kind: ManagedZone
metadata:
  name: queenswood-zone
  namespace: crossplane-system
spec:
  forProvider:
    dnsName: queenswood.repldriven.com.
    description: Queenswood public DNS
    visibility: public
