system:
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
  uk-companies-house-simulator-server:
    handler: !system/required-component
    state: !system/component
      system/component-kind: uk-companies-house-simulator/state
    interceptors: !system/component
      system/component-kind: server/interceptors
      state: !system/local-ref state
    jetty-adapter: !system/component
      system/component-kind: server/jetty-adapter
      handler: !system/ref uk-companies-house-simulator-server.handler
      interceptors: !system/ref uk-companies-house-simulator-server.interceptors
      options:
        port: 8084
    http-url: !system/component
      system/component-kind: server/http-url
      jetty-adapter: !system/local-ref jetty-adapter
