system:
  avro: !include system/avro.yml
  fdb: !include system/fdb-test.yml
  policies: !include system/policy-test.yml
  templates: !include system/templates-test.yml
  transactions: !include transaction/transactions-test.yml
