system:
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  policies: !include bank/policy-test.yml
  party:
    processor: !system/component
      system/component-kind: party/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
    watcher-handler: !system/component
      system/component-kind: party/watcher-handler
      record-store: !system/ref fdb.meta-store
    watchers: !system/component
      system/component-kind: fdb/watchers
      idvs:
        record-db: !system/ref fdb.record-db
        consumer-id: party-watcher
        store-name: idvs
        handler: !system/local-ref watcher-handler
