system:
  pulsar:
    client: !system/component
      system/component-kind: pulsar/client
      service-url: !env PULSAR_SERVICE_URL
    admin: !system/component
      system/component-kind: pulsar/admin
      service-http-url: !env PULSAR_ADMIN_URL
    schemas: !system/component
      system/component-kind: pulsar/schemas
      command:
        schema: schemas/command/command-envelope.avsc.json
        type: AVRO
      command-response:
        schema: schemas/command/command-response.avsc.json
        type: AVRO
      event:
        schema: schemas/event/event-envelope.avsc.json
        type: AVRO
    producers: !system/component
      system/component-kind: pulsar/producers
      payments-command-response:
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command-response
          topicName: "persistent://tenant-1/namespace-1/topic-payments-command-response"
        schemas: !system/local-ref schemas
      schemes-payment-command:
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command
          topicName: "persistent://tenant-1/namespace-1/topic-schemes-payment-command"
        schemas: !system/local-ref schemas
    consumers: !system/component
      system/component-kind: pulsar/consumers
      payments-command:
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-payment-service-payments-command
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-payments-command"]
        schemas: !system/local-ref schemas
      schemes-payments-event:
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-payment-service-schemes-payments-event
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-schemes-payments-event"]
        schemas: !system/local-ref schemas
    message-bus-producers: !system/component
      system/component-kind: pulsar/message-bus-producers
      payments-command-response:
        producer: !system/local-ref producers.payments-command-response
      schemes-payment-command:
        producer: !system/local-ref producers.schemes-payment-command
    message-bus-consumers: !system/component
      system/component-kind: pulsar/message-bus-consumers
      payments-command:
        consumer: !system/local-ref consumers.payments-command
      schemes-payments-event:
        consumer: !system/local-ref consumers.schemes-payments-event
  message-bus: !include bank/message-bus.yml
  fdb: !include bank/fdb.yml
  avro: !include bank/avro.yml
  banks:
    internal: !system/component
      system/component-kind: banks/bank-from-fdb
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      type: !keyword bank-type-internal
    internal-account-id: !system/component
      system/component-kind: banks/internal-account-id
      bank: !system/local-ref internal
  payments: !include bank/payment.yml
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
