system:
  server:
    port: !profile
      default: 80
      test: !port 0
    interceptors: !system/component
      type: server/interceptors
      got: me
      this: time
    jetty-adapter: !system/component
      type: server/jetty-adapter
      handler: !system/ref server.handler
      interceptors: !system/ref server.interceptors
      options:
        join?: false
        port: !system/ref server.port
