system:
  pulsar:
    client: !system/component
      system/component-kind: pulsar/client
      service-url: !env PULSAR_SERVICE_URL
    admin: !system/component
      system/component-kind: pulsar/admin
      service-http-url: !env PULSAR_ADMIN_URL
    schemas: !system/component
      system/component-kind: pulsar/schemas
      command:
        schema: schemas/command/command-envelope.avsc.json
        type: AVRO
      command-response:
        schema: schemas/command/command-response.avsc.json
        type: AVRO
      event:
        schema: schemas/event/event-envelope.avsc.json
        type: AVRO
    producers: !system/component
      system/component-kind: pulsar/producers
      payee-checks-command-response:
        client: !system/local-ref client
        conf:
          accessMode: !pulsar/access-mode Shared
          schema: !keyword command-response
          topicName: "persistent://tenant-1/namespace-1/topic-payee-checks-command-response"
        schemas: !system/local-ref schemas
    consumers: !system/component
      system/component-kind: pulsar/consumers
      payee-checks-command:
        client: !system/local-ref client
        conf:
          cryptoFailureAction: !pulsar/crypto-failure-action CONSUME
          schema: !pulsar/schema AUTO_CONSUME
          subscriptionName: bank-payee-check-service-payee-checks-command
          subscriptionType: !pulsar/subscription-type Shared
          topicNames:
            ["persistent://tenant-1/namespace-1/topic-payee-checks-command"]
        schemas: !system/local-ref schemas
    message-bus-producers: !system/component
      system/component-kind: pulsar/message-bus-producers
      payee-checks-command-response:
        producer: !system/local-ref producers.payee-checks-command-response
    message-bus-consumers: !system/component
      system/component-kind: pulsar/message-bus-consumers
      payee-checks-command:
        consumer: !system/local-ref consumers.payee-checks-command
  message-bus: !include bank/message-bus.yml
  fdb: !include bank/fdb.yml
  avro: !include bank/avro.yml
  payee-checks: !include bank/payee-check.yml
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
