system:
  postgres: !include testcontainers/postgres-test.yml
  db: !include processor/postgres/datasource-test.yml
  migrator:
    migrations: !system/component
      system/component-kind: migrator/migrations
      datasource: !system/ref db.datasource
      changelogs:
        - schemas/accounts/init-changelog.sql
  processor:
    datasource: !system/ref migrator.migrations
