system:
  kafka:
    schemas: !system/component
      system/component-kind: avro/serde
      schemas:
        command: schemas/command/command-envelope.avsc.json
        command-response: schemas/command/command-response.avsc.json
        event: schemas/event/event-envelope.avsc.json
    producers: !system/component
      system/component-kind: kafka/producers
      idv-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-idv-command-response
          acks: all
      idv-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-idv-event
          acks: all
    consumers: !system/component
      system/component-kind: kafka/consumers
      idv-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-idv-command]
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: onfido-adapter-service-idv-command
    message-bus-producers: !system/component
      system/component-kind: kafka/message-bus-producers
      idv-command-response:
        producer: !system/local-ref producers.idv-command-response
      idv-event:
        producer: !system/local-ref producers.idv-event
    message-bus-consumers: !system/component
      system/component-kind: kafka/message-bus-consumers
      idv-command:
        consumer: !system/local-ref consumers.idv-command
        timeout: 500
  message-bus: !include system/message-bus.yml
  fdb: !include system/fdb.yml
  avro: !include system/avro.yml
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
  onfido-adapter: !include system/onfido-adapter.yml
  onfido-adapter-server: !include system/onfido-adapter-server.yml
