system:
  kafka: !include system/kafka-bootstrap.yml
  fdb: !include system/fdb.yml
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
