syntax = "proto2";

package com.repldriven.mono.schemas.assertion;

import "record_metadata_options.proto";

option java_outer_classname = "AssertionProto";

message Assertion {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  optional string assertion_id = 1;
  optional string party_id = 2;
  optional string bank_id = 3;

  optional Issuer issuer = 4;
  optional AssertionKind kind = 5;

  required int64 created_at = 6;

  reserved 101;

  oneof value {
    IndividualContactDetailsAssertion individual_contact_details = 102;
  }
}

enum AssertionKind {
  ASSERTION_KIND_UNKNOWN = 0;
  ASSERTION_KIND_INDIVIDUAL_IDENTITY = 1;
  ASSERTION_KIND_INDIVIDUAL_RESIDENCE = 2;
  ASSERTION_KIND_INDIVIDUAL_CONTACT_DETAILS = 3;
  ASSERTION_KIND_INDIVIDUAL_NATIONALITY = 4;
  ASSERTION_KIND_CORPORATION_REGISTRATION = 10;
  ASSERTION_KIND_CORPORATION_FINANCIAL_SERVICE = 11;
  ASSERTION_KIND_CORPORATION_TAX_RESIDENCE = 12;
  ASSERTION_KIND_REVOCATION = 99;
}

message IndividualContactDetailsAssertion {
  optional string display_name = 1;
  optional string email_address = 2;
  optional string phone_number = 3;
}

message Issuer {
  optional IssuerKind kind = 1;
  optional string source = 2;
}

enum IssuerKind {
  ISSUER_KIND_UNKNOWN = 0;
  ISSUER_KIND_CUSTOMER_SELF_DECLARED = 1;
  ISSUER_KIND_OPERATOR = 2;
  ISSUER_KIND_THIRD_PARTY = 3;
  ISSUER_KIND_DOCUMENT_EXTRACTED = 4;
}
