{{- if and .Values.ingress.enabled .Values.ingress.gcp.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "queenswood.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
