{{- if and .Values.ingress.enabled .Values.ingress.gcp.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-cert
  labels:
    {{- include "queenswood.labels" . | nindent 4 }}
spec:
  domains:
    - {{ .Values.ingress.host | quote }}
{{- end }}
