apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin-api-key
  labels:
    {{- include "queenswood.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONO_ADMIN_API_KEY: {{ required ".Values.secrets.adminApiKey is required" .Values.secrets.adminApiKey | quote }}
