{{- range $svcName, $svc := .Values.services }}
{{- if and $svc.enabled $svc.http }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $svcName }}
  labels:
    {{- include "queenswood.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $svcName }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $svcName }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
    {{- range $extra := $svc.extraPorts }}
    - name: {{ $extra.name }}
      port: {{ $extra.port }}
      targetPort: {{ $extra.name }}
      protocol: TCP
    {{- end }}
{{- end }}
{{- end }}
