system:
  fdb: !include testcontainers/fdb-test.yml
  avro: !include avro/avro-test.yml
  idv:
    processor: !system/component
      system/component-kind: idv/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.store
      schemas: !system/ref avro.serde
    watcher-handler: !system/component
      system/component-kind: idv/watcher-handler
      record-store: !system/ref fdb.store
    watcher: !system/component
      system/component-kind: fdb/watcher
      record-db: !system/ref fdb.record-db
      consumer-id: idv-watcher
      store-name: idvs
      handler: !system/local-ref watcher-handler
