apiVersion: platform.queenswood.repldriven.com/v1alpha1
kind: XQueenswoodApex
metadata:
  name: {{ .Values.env.name }}-apex
  namespace: {{ .Values.env.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    description: Queenswood static IP + apex DNS records
spec:
  region: {{ .Values.apex.region }}
  addressType: EXTERNAL
  domain: {{ .Values.env.domain }}
  managedZoneRef:
    name: {{ .Values.env.name }}-zone
