apiVersion: platform.queenswood.repldriven.com/v1alpha1
kind: XQueenswoodCertificate
metadata:
  name: {{ .Values.env.name }}-cert
  namespace: {{ .Values.env.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    description: Queenswood TLS certificate
spec:
  domain: {{ .Values.env.domain }}
  location: {{ .Values.cert.location }}
  managedZoneRef:
    name: {{ .Values.env.name }}-zone
