system:
  pulsar: !include bank-scenario-runner/pulsar-test.yml
  message-bus: !include bank-scenario-runner/message-bus-test.yml
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  policies: !include bank/policy-test.yml
  organizations: !include bank/organization-test.yml
  idv: !include bank/idv-test.yml
  parties: !include bank-scenario-runner/party-test.yml
  onfido-simulator-server: !include bank-scenario-runner/onfido-simulator-test.yml
  onfido-adapter-server: !include bank-scenario-runner/onfido-adapter-server-test.yml
  onfido-adapter: !include bank-scenario-runner/onfido-adapter-test.yml
