system:
  sql:
    container: !system/component
      kind: sql/container
      docker-image-name: postgres:16
      exposed-port: 5432

    container-mapped-exposed-port: !system/component
      kind: sql/container-mapped-exposed-port
      container: !system/local-ref container
      exposed-port: 5432

    datasource: !system/component
      kind: sql/datasource
      database: test
      dbtype: postgres
      host: localhost
      password: test
      port: !system/local-ref container-mapped-exposed-port
      user: test
