system:
  mqtt: !include testcontainers/mqtt-test.yml
  pulsar: !include testcontainers/pulsar-all-test.yml
  postgres: !include testcontainers/postgres-test.yml
  db: !include pulsar-mqtt-processor/datasource-test.yml
  processor:
    datasource: !system/ref db.datasource
