(ns com.repldriven.queenswood.monolith.system
  (:require
    com.repldriven.queenswood.bank.interface
    com.repldriven.queenswood.cash-account.interface
    com.repldriven.queenswood.changelog-relay.interface
    com.repldriven.queenswood.clearbank-adapter.system
    com.repldriven.queenswood.clearbank-simulator.system
    com.repldriven.queenswood.clearbank-webhook.interface
    com.repldriven.queenswood.idv.interface
    com.repldriven.mono.identity-provider.interface
    com.repldriven.mono.keycloak.interface
    com.repldriven.queenswood.membership.interface
    com.repldriven.queenswood.onfido-adapter.system
    com.repldriven.queenswood.onfido-simulator.system
    com.repldriven.queenswood.onfido-webhook.interface
    com.repldriven.queenswood.uk-companies-house-simulator.system
    com.repldriven.queenswood.interest.interface
    com.repldriven.queenswood.party.interface
    com.repldriven.queenswood.payment.interface
    com.repldriven.queenswood.scheduler.interface
    com.repldriven.queenswood.schema.interface
    com.repldriven.queenswood.transaction.interface
    com.repldriven.queenswood.user.interface

    com.repldriven.mono.command.interface
    com.repldriven.mono.command-processor.interface
    com.repldriven.mono.event-processor.interface
    com.repldriven.mono.fdb.interface
    com.repldriven.mono.kafka.interface
    com.repldriven.mono.message-bus.interface
    com.repldriven.mono.scheduler.interface
    com.repldriven.mono.server.interface))
