syntax = "proto2";

package com.repldriven.queenswood.schemas.person_identification;

import "record_metadata_options.proto";

option java_outer_classname = "PersonIdentificationProto";

message Address {
  optional string flat_number     = 1;
  optional string building_number = 2;
  optional string building_name   = 3;
  required string street          = 4;
  optional string sub_street      = 5;
  required string town            = 6;
  optional string state           = 7;
  required string postcode        = 8;
  required string country         = 9;  // ISO 3166-1 alpha-3
  optional string start_date      = 10; // ISO 8601 YYYY-MM-DD
}

message PersonIdentification {
  option (com.apple.foundationdb.record.record).usage = RECORD;

  required string party_id = 1 [(com.apple.foundationdb.record.field).primary_key = true];

  required string given_name = 2;
  optional string middle_names = 3;
  required string family_name = 4;
  required int32 date_of_birth = 5; // YYYYMMDD
  required string nationality = 6; // ISO 3166-1 alpha-2

  required Address address = 7;

  required int64 created_at = 8;
  required int64 updated_at = 9;
}
