system:
  kafka:
    schemas: !system/component
      system/component-kind: avro/serde
      schemas:
        command: schemas/command/command-envelope.avsc.json
        command-response: schemas/command/command-response.avsc.json
        event: schemas/event/event-envelope.avsc.json
    producers: !system/component
      system/component-kind: kafka/producers
      schemes-payment-command-response:
        schemas: !system/local-ref schemas
        schema: !keyword command-response
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-schemes-payment-command-response
          acks: all
      schemes-payments-event:
        schemas: !system/local-ref schemas
        schema: !keyword event
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-schemes-payments-event
          acks: all
      schemes-payment-command-dlq:
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          topic: topic-schemes-payment-command-dlq
          acks: all
    consumers: !system/component
      system/component-kind: kafka/consumers
      schemes-payment-command:
        schemas: !system/local-ref schemas
        schema: !keyword command
        topics: [topic-schemes-payment-command]
        dead-letter-producer: !system/local-ref producers.schemes-payment-command-dlq
        max-redeliveries: 5
        conf:
          bootstrap.servers: !env KAFKA_BOOTSTRAP_SERVERS
          group.id: clearbank-adapter-service-schemes-payment-command
    message-bus-producers: !system/component
      system/component-kind: kafka/message-bus-producers
      schemes-payment-command-response:
        producer: !system/local-ref producers.schemes-payment-command-response
      schemes-payments-event:
        producer: !system/local-ref producers.schemes-payments-event
    message-bus-consumers: !system/component
      system/component-kind: kafka/message-bus-consumers
      schemes-payment-command:
        consumer: !system/local-ref consumers.schemes-payment-command
        timeout: 500
  message-bus: !include system/message-bus.yml
  fdb: !include system/fdb.yml
  avro: !include system/avro.yml
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
  clearbank-adapter: !include system/clearbank-adapter.yml
  clearbank-adapter-server: !include system/clearbank-adapter-server.yml
