system:
  telemetry:
    otel-sdk: !system/component
      system/component-kind: telemetry/otel-sdk
      service-name: !env SERVICE_NAME
      endpoint: !env OTEL_ENDPOINT
  onfido-simulator-server: !include system/onfido-simulator-server.yml
