system:
  fdb: !include bank/fdb-test.yml
  avro: !include avro/avro-test.yml
  policies: !include bank/policy-test.yml
  organizations: !include bank/organization-test.yml
  transactions:
    processor: !system/component
      system/component-kind: transactions/processor
      record-db: !system/ref fdb.record-db
      record-store: !system/ref fdb.meta-store
      schemas: !system/ref avro.serde
