postgresql:
  mode: external
  external:
    proxy:
      connectionName: queenswood-820d84:europe-west2:queenswood-keycloak
      gcpServiceAccount: keycloak-sql-proxy@queenswood-820d84.iam.gserviceaccount.com
