system:
  db:
    container: !system/component
      system/component-kind: postgres/container
      exposed-port: 5432

    container-mapped-exposed-port: !system/component
      system/component-kind: postgres/container-mapped-exposed-port
      container: !system/local-ref container
      exposed-port: 5432

    datasource: !system/component
      system/component-kind: db/datasource
      database: test
      dbtype: postgres
      host: localhost
      password: test
      port: !system/local-ref container-mapped-exposed-port
      user: test

  server:
    handler: !system/required-component

    interceptors: !system/component
      system/component-kind: server/interceptors
      datasource: !system/ref db.datasource

    jetty-adapter: !system/component
      system/component-kind: server/jetty-adapter
      handler: !system/ref server.handler
      interceptors: !system/ref server.interceptors
      options:
        join?: !profile
          default: false
        port: !profile
          default: !port 8080
          test: !port 0
