:PORT = 56929

# get
GET http://localhost::PORT/v1/projects/prj-12345/serviceAccounts

# create
POST http://localhost::PORT/v1/projects/prj-12345/serviceAccounts
Content-Type: application/json
{ "account-id": "sa-123",
  "service-account": {
    "display-name": "sa 123",
    "description": "My First Service Account"
  }
}
