#!/usr/bin/env bash
set -e

files=$(git diff --cached --name-only --diff-filter=ACM \
  | grep -E '\.(clj|cljc|cljs)$' \
  | while read -r f; do [ -f "$f" ] && echo "$f"; done)

if [ -n "$files" ]; then
  echo "Formatting Clojure files..."
  echo "$files" | xargs clojure -M:format/zprint -w
  echo "$files" | xargs git add

  echo "Linting Clojure files..."
  clojure -M:lint/clj-kondo --lint bases components development
fi
